# Generated by Django 5.1.1 on 2024-09-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='api.roles'),
        ),
    ]
