# Generated by Django 5.1.1 on 2024-10-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_cantidad_pago_subtotal_remove_pago_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='stripe_checkout_id',
            new_name='payment_intent_id',
        ),
    ]
